### ISSUE TITLE
Integrate OPhase to Neuland.app for "Ersties"

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/THI-App#70] opened 2021-08-14 12:50 UTC
If we integrate Ophase to the NeulandApp we might get new Users and inform new students about the life as a student in Ingolstadt more efficiently than opening a diffrent page.

**Comment by alexhorn** [comment] 2021-08-14 12:51
Duplicate of #60

**Closed by alexhorn** 2021-08-14 12:51 UTC
Labels: duplicate
