### ISSUE TITLE
annoying error message if no bus times are available

### ISSUE THREAD

**Issue by Schrottpage** [neuland-ingolstadt/THI-App#43] opened 2021-04-23 20:36 UTC
![image](https://user-images.githubusercontent.com/39926202/115927103-32367480-a484-11eb-88c0-a738794c9e53.png)

**Comment by M4GNV5** [comment] 2021-04-23 20:39
blame INVG

**Comment by M4GNV5** [comment] 2021-04-23 21:05
duplicate of #33

**Closed by M4GNV5** 2021-04-23 21:05 UTC
Labels: bug, duplicate
