### ISSUE TITLE
Timetable broken when viewing next month

### ISSUE THREAD

**Issue by FabianSimonGross** [neuland-ingolstadt/THI-App#79] opened 2021-09-15 19:42 UTC
![grafik](https://user-images.githubusercontent.com/81598210/133498876-a1b6953b-fe39-4c90-926e-edbfaec06438.png)

**Comment by FabianSimonGross** [comment] 2021-09-15 19:43
and another one
![grafik](https://user-images.githubusercontent.com/81598210/133499048-b91cb807-7b31-4bab-8d2f-b2a275edc2ed.png)

**Comment by M4GNV5** [comment] 2021-09-15 19:52
We cannot reproduce this issue here, it looks like there is a room missing in your timetable data. Can you post the JSON output of your timetable?

You can retrieve it using the [API debug tools ("API Spielwiese")](https://neuland.app/debug):

![Screenshot from 2021-09-15 20-50-59](https://user-images.githubusercontent.com/5504713/133500102-04f9d67a-b9d0-42e9-82ac-e808826ffbb6.png)

**Comment by FabianSimonGross** [comment] 2021-09-15 19:59
https://pastebin.com/TSFybihh

It's from a first semester. Sooo

**Comment by alexhorn** [comment] 2021-09-15 20:08
Thanks, fixed in e9b93a442877932f3f2513e386eadeecd6d1427b

**Closed by alexhorn** 2021-09-15 20:08 UTC
Labels: bug
